name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          cache: 'pipenv'
      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      - name: Install Python dependencies
        run: pipenv install --dev
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v5
        with:
          node-version: '18'
          cache: 'yarn'
      - name: Install Node.js dependencies
        run: yarn install --immutable
      - name: Run tests
        run: |
          pipenv run python test.py
          pipenv run python annotate_schema.py -m hf-internal-testing/tiny-random-GPTBigCodeForCausalLM -t 10 -i test.json -o test-desc.json
          pipenv run python annotate_schema.py -m hf-internal-testing/tiny-random-GPTBigCodeForCausalLM -t 10 -s pydantic -i test.json
          pipenv run python annotate_schema.py -m hf-internal-testing/tiny-random-GPTBigCodeForCausalLM -t 10 -s typescript -i test.json
          pipenv run python annotate_schema.py -m hf-internal-testing/tiny-random-GPTBigCodeForCausalLM -t 10 -s zod -i test.json
          pipenv run python name_definitions.py -m hf-internal-testing/tiny-random-BertForMaskedLM  --no-strip-existing -i test-desc.json -o test-final.json
          pipenv run python eval.py -s abstractness -d -n test-final.json test.json
